name: CI BE

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Executing remote ssh command
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: 22
        script: |
            cd backend-main-server
            git reset --hard
            git pull

            # Stop docker compose 
            docker compose down && docker image prune -f

            # Build docker compose
            docker compose build

            # Run docker compose
            docker compose up -d